### ISSUE TITLE
Clashing `Result` types

### ISSUE THREAD

**Issue by BenLeadbetter** [luker-os/variantly#10]
Hi. 

Nice crate! 😊 

I'd really like to use this for another crate I'm working on.  I've got a compile issue, though. The generated code from the Variantly derive macro is using the `Result` type from the standard rust prelude (in the global namespace). This clashes with my own crate's custom `Result` type.

The fix should be pretty easy: fully qualify all uses in the generated code like this: `core::result::Result`. I applied this patch to the 0.3.0 version and it worked nicely. 👍 

I was going to open a PR against develop, but it seems develop is in quite a different state to 0.3.0 - many generated methods from 0.3.0 seem to be missing. I wonder whether it would be possible to do a 0.3.1 hotfix which would include this bugfix patch?

Thanks!
Ben

**Comment by luker-os** [comment]
Hello & thank you! Glad you like the crate and thanks for the call-out! 

`develop` is not being used currently - in fact, I should probably nuke it. If you've got one ready to go, a PR against `main` would be welcome, otherwise I should be able to add this and release it tonight/tomorrow

**Comment by BenLeadbetter** [comment]
Thanks! 🥇

**Comment by luker-os** [comment]
np! This has now been released:
https://crates.io/crates/variantly/0.4.0
