### ISSUE TITLE
[docs] Derived function naming example mistake

### ISSUE THREAD

**Issue by drmason13** [luker-os/variantly#2]
As far as I can tell, the following example in the Readme is slightly wrong:

```
use inflector::cases::snakecase::to_snake_case;

fn name_fn(operation: String, variant_name: String) -> String {
    let snake_case_variant = to_snake_case(&variant_name);
    format!("{}_{}", snake_case_variant, operation) // swap the arguments here
}

#[test]
fn it_makes_a_name() {
    assert_eq!(
        name_fn("unwrap","VariantA"),
        "unwrap_variant_a".into()
    )
}
```

The operation goes in front, so the function should return
```
format!("{}_{}", operation, snake_case_variant)
```

Love the crate, saw it featured on crate of the week, congrats!
Am on mobile, otherwise would be happy to provide a pull request!

**Comment by luker-os** [comment]
Ah, you are correct. Thanks for catching that & calling it out! I'll get that corrected shortly.
